name: Check if PR is approved and mergeable

on:
  pull_request_review:
    types: [submitted]
    branches:
     - 'releases'

jobs:
  check-pr:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'releases'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is approved and mergeable
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          retries: 3
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
            
            const response = await github.rest.pulls.get({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number
            });

            if ((response.data.mergeable) && !response.data.requested_teams.includes("change-review-board")) {
              console.log('PR is mergeable and CRB is not listed');
            } else {
              console.log('PR is not mergeable')
              console.log('CRB IS LISTED ?', response.data.requested_teams.includes("change-review-board"));
            }
            console.log(response);
            
            
            
