name: Check if PR is approved and mergeable

on:
  pull_request_review:
    types: [submitted]
    branches:
     - 'releases'

jobs:
  check-pr:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is approved and mergeable
        id: pr-check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
          
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number
            });

            const { data: crbMembers } = await github.rest.teams.listMembersInOrg({
              org: 'january67',
              team_slug: 'change-review-board',
            });
            
            let approvedByCrb = false;
            approvedByCrb = reviews.some(review => crbMembers.some(member => member.login === review.user.login));
            console.log(approvedByCrb);
            if(!approvedByCrb){
              core.setFailed("No members of CRB approved the pull request");
            }
            return approvedByCrb;
            
            
              
#       - name: Merge pull request
#         uses: actions/github-script@v6
       
#         with:
#           github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           script: |
#             const pr = context.payload.pull_request;
#             const merge = await github.rest.pulls.merge({
#               owner: pr.base.repo.owner.login,
#               repo: pr.base.repo.name,
#               pull_number: pr.number,
#               merge_method: "merge"
#             });
#             console.log('MERGED', merge);
      
        
        
            
      - name: Trigger CircleCI Release
        run: |
          echo ${{ github.event.pull_request.number }}
          
          curl --request POST \
            --url https://circleci.com/api/v2/project/github/january67/mobile-release-automation/pipeline \
            --header 'authorization: Basic ${{ secrets.CIRCLE_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{"branch":"main","parameters":{"merge_rc_pr":true, "pr_number": "${{ github.event.pull_request.number }}", "rc_pr_title": "${{ github.event.pull_request.title }}"}}'
            
            
            
            


            
            
           
