name: Check if PR is approved and mergeable

on:
  pull_request_review:
    types: [submitted]
    branches:
     - 'releases'

jobs:
  check-pr:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'releases'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is approved and mergeable
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          retries: 3
          result-encoding: string
          script: |
            const pr = context.payload.pull_request;
            
            const response = await github.rest.pulls.get({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number
            });
            const reviewsResponse = await github.rest.pulls.listReviews({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number
            });
            const reviews = reviewsResponse.data;
            
            const teamResponse = await github.rest.teams.listMembers({
              team_id: 7140016,
            });
            const teamMembers = teamResponse.data;
            
            for (const review of reviews){
              if(review.state === 'APPROVED'){
                const user = review.user.login;
                if (teamMembers.find((member) => member.login === user)) {
                console.log(`${user} is a member of the "change-review-board" team`);
                }
              }
            }
            console.log(reviews);
            console.log(response.data.requested_teams);
            console.log('IS SLUG CRB?', response.data.requested_teams.slug == 'change-review-board');
            console.log('OBJ?', response.data.requested_teams?.slug == 'change-review-board');
            //for (const team of response.data?.requested_teams){
            //  if (team.slug.includes("change-review-board")){
            //    console.log("CRB IS FOUND, REVIEW NOT COMPLETED");
            //  }
            //}
            if (response.data?.requested_teams.length === 0) {
              console.log("The requested_teams array is empty");
            } else {
              for (const team of response.data?.requested_teams) {
                if (team.slug.includes("change-review-board")) {
                  console.log("CRB IS FOUND, REVIEW NOT COMPLETED");
                }
              }
            }

            //if ((response.data.mergeable) && !response.data.requested_teams.slug == 'change-review-board')) {
            //  console.log('PR is mergeable and CRB is not listed');
            //  const merge = await github.rest.pulls.merge({
            //    owner: pr.base.repo.owner.login,
            //    repo: pr.base.repo.name,
            //    pull_number: pr.number
            //  });
            //  console.log('MERGED', merge);
            //} else {
            //  console.log('PR is not mergeable')
            //  console.log('CRB IS LISTED ?', response.data.requested_teams.includes("change-review-board"));
            //}
            console.log(response);
            
            
            
